<%-- 
    Document   : terms
    Created on : Sep 13, 2017, 10:25:34 PM
    Author     : Lovreone
--%>

<%@page contentType="text/html" pageEncoding="UTF-8"%>
<!DOCTYPE html>
<html>
    <head>
        <title>Terms and Conditions</title>
        <%@include file="head-meta.jsp"%>
    </head>
    <body>
        <%@include file="main-nav.jsp"%>
        <div class="container stylish-div-background"> <!-- https://www.colourandtrends.com/privacy -->
            <h2>Terms &AMP; Conditions</h2>

            <div class="inner-div">
                <p><b>USER TERMS & CONDITIONS</b></p>
                <p>PLEASE READ THE FOLLOWING TERMS AND CONDITIONS CAREFULLY</p>
                <p>THE WEBSTORE INC WEB SITE (THE “WEB SITE” OR “WEBSTORE.COM”) IS PROVIDED BY WEBSTORE INC FOR YOUR AND OTHERS’ ENJOYMENT, SUBJECT TO THE TERMS OF THESE TERMS AND CONDITIONS OF USE AND ALL MODIFICATIONS THERETO (“TERMS AND CONDITIONS”), AND THE RULES THAT MAY BE PUBLISHED FROM TIME TO TIME BY WEBSTORE INC. BY USING THIS SITE, YOU ARE DEEMED TO HAVE AGREED TO THESE TERMS AND CONDITIONS OF USE. WEBSTORE INC MAY CHANGE THE TERMS AND CONDITIONS FROM TIME TO TIME AND AT ANY TIME, AND WITHOUT ACTUAL NOTICE TO YOU. ALL SUCH CHANGES TO THESE TERMS AND CONDITIONS WILL APPEAR ON WWW.WEBSTORE.COM. BY USING THIS SITE AFTER WE POST ANY CHANGES, YOU AGREE TO ACCEPT THOSE CHANGES, WHETHER OR NOT YOU HAVE REVIEWED THEM. IF AT ANY TIME YOU CHOOSE NOT TO ACCEPT THESE TERMS AND CONDITIONS OF USE, PLEASE DO NOT USE THIS SITE.</p>

                <p><b>USER CONDUCT</b></p>
                <p>THIS WEB SITE AND ANY COMMUNICATIONS SERVICE, INCLUDING THE CAPABILITY TO CONTRIBUTE MATERIAL IN ANY FORMAT TO THE SITE IS PROVIDED TO YOU SOLELY FOR ENTERTAINMENT PURPOSES. BY SUBMITTING SUCH MATERIAL TO WEBSTORE INC (EACH, A “CONTRIBUTION), YOU ACKNOWLEDGE AND AGREE THAT WEBSTORE INC HAS A WORLDWIDE, ROYALTY-FREE LICENSE RIGHT TO PUBLISH, DISPLAY, DISTRIBUTE SUBLICENSE, MAKE AVAILABLE TO END USERS OR REUSE IN ANY MANNER SUCH CONTRIBUTIONS. YOU ALSO ACKNOWLEDGE AND AGREE THAT THE DECISION TO PUBLISH SUCH CONTRIBUTION IS SOLELY AT THE DISCRETION OF WEBSTORE INC. BY USING THE WEB SITE AND SERVICES YOU AGREE: (A) TO PROVIDE TRUE, ACCURATE, CURRENT AND COMPLETE INFORMATION ABOUT YOURSELF AS PROMPTED BY THE SUBSCRIPTION FORM, CONTRIBUTION FORM AND ANY REGISTRATION FORM. IF ANY INFORMATION PROVIDED BY YOU IS UNTRUE, INACCURATE, NOT CURRENT OR INCOMPLETE, WEBSTORE INC RESERVES THE RIGHT TO TERMINATE YOUR SUBSCRIPTION AND REFUSE ANY AND ALL CURRENT OR FUTURE USE OF THE SERVICES.></p>

                <p>WITHOUT LIMITATION OF THE FOREGOING, YOU AGREE TO NOT USE THE WEB SITE OR SERVICES TO:</p>
                <ul>
                    <li>UPLOAD, POST, PUBLISH, E-MAIL, REPRODUCE, DISTRIBUTE OR OTHERWISE TRANSMIT ANY INFORMATION, DATA, TEXT, MUSIC, SOUND, PHOTOGRAPHS, GRAPHICS, VIDEO, MESSAGES OR OTHER MATERIALS, INCLUDING ANY CONTRIBUTION, (COLLECTIVELY, “CONTENT”), THAT IS UNLAWFUL, HARMFUL, THREATENING, EMBARRASSING, ABUSIVE, HARASSING, TORTIOUS, DEFAMATORY, VULGAR, OBSCENE, LIBELOUS, DECEPTIVE, FRAUDULENT, CONTAINS EXPLICIT OR GRAPHIC DESCRIPTIONS OR ACCOUNTS OF SEXUAL ACTS, INVASIVE OF ANOTHER’S PRIVACY, OR HATEFUL;
                    <li>HARM MINORS IN ANY WAY;</li>
                    <li>IMPERSONATE ANY PERSON OR ENTITY, INCLUDING, BUT NOT LIMITED TO, A WEBSTORE INC. OFFICIAL, OR FALSELY STATE OR OTHERWISE MISREPRESENT YOUR AFFILIATION WITH A PERSON OR ENTITY;</li>
                    <li>FORGE HEADERS OR OTHERWISE MANIPULATE IDENTIFIERS IN ORDER TO DISGUISE THE ORIGIN OF ANY CONTENT TRANSMITTED TO OR THROUGH THE WEB SITE;</li>
                    <li>UPLOAD, POST, PUBLISH, E-MAIL, REPRODUCE, DISTRIBUTE OR OTHERWISE TRANSMIT ANY CONTENT THAT INFRINGES ANY PATENT, TRADEMARK, TRADE SECRET, COPYRIGHT OR OTHER PROPRIETARY RIGHTS OF ANY PARTY;</li>
                    <li>UPLOAD, POST, PUBLISH, E-MAIL, REPRODUCE, DISTRIBUTE OR OTHERWISE TRANSMIT ANY UNSOLICITED OR UNAUTHORIZED ADVERTISING, PROMOTIONAL MATERIALS, “JUNK MAIL,” “SPAM,” “CHAIN LETTERS,” “PYRAMID SCHEMES,” OR ANY OTHER FORM OF SOLICITATION;</li>
                    <li>UPLOAD, POST, PUBLISH, E-MAIL, REPRODUCE, DISTRIBUTE OR OTHERWISE TRANSMIT ANY MATERIAL THAT CONTAINS SOFTWARE VIRUSES, TROJAN HORSES, WORMS, TIME BOMBS, CANCELBOTS, OR ANY OTHER COMPUTER CODE, FILES OR PROGRAMS DESIGNED TO INTERRUPT, DESTROY, OR LIMIT THE FUNCTIONALITY OF ANY COMPUTER SOFTWARE OR HARDWARE OR TELECOMMUNICATIONS EQUIPMENT OR ANY OTHER SIMILARLY DESTRUCTIVE ACTIVITY, OR SURREPTITIOUSLY INTERCEPT OR EXPROPRIATE ANY SYSTEM, DATA OR PERSONAL INFORMATION;</li>
                    <li>ACT IN A MANNER THAT NEGATIVELY AFFECTS OTHER USERS’ ABILITY TO ENGAGE IN THE WEB SITE OR SERVICES;</li>
                    <li>ENGAGE IN ANY ACTIVITY THAT IS CONTRARY TO OR WHICH WOULD ADVERSELY AFFECT THE PURPOSE OR INTENTION OF THE WEB SITE OR SERVICES, INCLUDING BUT NOT LIMITED TO, ACTUALLY OR ATTEMPTING TO MANIPULATE, CORRUPT OR OTHERWISE AFFECT THE OUTCOME OF THE SERVICES, IN WHOLE OR PART, BY, AMONG OTHER METHODS, SUBSCRIBING ANOTHER PARTY WITHOUT THEIR AUTHORIZATION OR REGISTERING MULTIPLE SUBSCRIPTIONS UNDER THE SAME OR DIFFERENT NAMES;</li>
                    <li>INTERFERE WITH OR DISRUPT THE SERVICE OR SERVERS OR NETWORKS CONNECTED TO THE SERVICE, OR DISOBEY ANY REQUIREMENTS, PROCEDURES, POLICIES OR REGULATIONS OF NETWORKS CONNECTED TO THE SERVICE; OR</li>
                    <li>INTENTIONALLY OR UNINTENTIONALLY VIOLATE ANY APPLICABLE LOCAL, STATE, NATIONAL OR INTERNATIONAL LAW.</li>
                </ul>

                <p>YOU ALSO AGREE THAT YOU WILL NOT HARVEST, COLLECT OR STORE INFORMATION ABOUT THE USERS OF THIS WEB SITE OR THE CONTENT POSTED BY OTHERS ON THIS WEB SITE OR USE SUCH INFORMATION FOR ANY PURPOSE INCONSISTENT WITH THE PURPOSE OF THIS WEB SITE OR FOR THE PURPOSE OF TRANSMITTING OR FACILITATING TRANSMISSION OF UNSOLICITED BULK ELECTRONIC MAIL OR COMMUNICATIONS.</p>

                <p>YOU ACKNOWLEDGE THAT WEBSTORE INC. IS NOT RESPONSIBLE FOR MATERIAL SUBMITTED TO WEBSTORE INC. OR POSTED TO THE WEB SITE BY USERS. WEBSTORE INC. DOES NOT PRE-SCREEN, MONITOR, REVIEW OR EDIT THE CONTENT POSTED BY USERS. HOWEVER, WEBSTORE INC. AND ITS DESIGNEES HAVE THE RIGHT (BUT NOT THE OBLIGATION) AT THEIR SOLE DISCRETION TO REFUSE OR REMOVE ANY CONTENT, IN WHOLE OR PART, THAT, IN WEBSTORE INC.'S JUDGMENT, DOES NOT COMPLY WITH THESE TERMS AND CONDITIONS OR IS OTHERWISE UNDESIRABLE, INAPPROPRIATE OR INACCURATE. WEBSTORE INC. IS NOT RESPONSIBLE FOR ANY FAILURE, NON-FAILURE OR DELAY IN REMOVING SUCH CONTENT. YOU WILL REMAIN RESPONSIBLE FOR THE ACCURACY, COPYRIGHT COMPLIANCE, LEGALITY, DECENCY, OR ANY OTHER ASPECT OF SUCH SUBMITTED MATERIAL, INCLUDING ANY CONTRIBUTION OR PART THEREOF, OR OTHER COMMUNICATION TO WEBSTORE INC. YOU AGREE TO IMMEDIATELY NOTIFY WEBSTORE INC. OF ANY UNAUTHORIZED USE OF THE SERVICE OR ANY OTHER BREACH OF SECURITY KNOWN OR SUSPECTED BY YOU.</p>

                <p>YOU ACKNOWLEDGE AND AGREE THAT WEBSTORE INC. MAY PRESERVE CONTENT AND MAY ALSO DISCLOSE CONTENT IF REQUIRED TO DO SO BY LAW OR IN THE GOOD FAITH BELIEF THAT SUCH PRESERVATION OR DISCLOSURE IS REASONABLY NECESSARY TO: (A) COMPLY WITH LEGAL PROCESS; (B) ENFORCE THESE TERMS AND CONDITIONS; (C) RESPOND TO CLAIMS THAT ANY CONTENT VIOLATES THE RIGHTS OF THIRD-PARTIES; OR (D) PROTECT THE RIGHTS, PROPERTY, OR PERSONAL SAFETY OF WEBSTORE INC., ITS USERS OR THE PUBLIC.</p>

                <p>YOU UNDERSTAND THAT THE TECHNICAL PROCESSING AND TRANSMISSION OF THE WEB SITE, INCLUDING YOUR CONTENT, MAY INVOLVE (A) TRANSMISSIONS OVER VARIOUS NETWORKS; AND (B) CHANGES TO CONFORM AND ADAPT TO TECHNICAL REQUIREMENTS OF CONNECTING NETWORKS OR DEVICES. WEBSTORE INC. ASSUMES NO RESPONSIBILITY FOR THE DELETION OR FAILURE TO STORE POSTINGS, CONTRIBUTIONS OR OTHER INFORMATION SUBMITTED BY YOU OR OTHER USERS TO WEBSTORE.COM.</p>

                <p>ANY OR ALL CONTENT ON THE WEB SITE MAY BE PURGED PERIODICALLY IN WEBSTORE INC.'S SOLE DISCRETION. YOU ACKNOWLEDGE AND AGREE THAT CONTENT YOU VIEW, SUBMIT OR POST IS AT YOUR OWN DISCRETION AND RISK, INCLUDING ANY RELIANCE ON THE ACCURACY, COMPLETENESS, OR USEFULNESS OF SUCH CONTENT. YOU ACKNOWLEDGE THAT YOU MAY NOT RELY ON ANY INFORMATION, DATA, TEXT, PHOTOGRAPHS, GRAPHICS, MESSAGES OR OTHER MATERIALS CREATED BY WEBSTORE INC. OR SUBMITTED TO WEBSTORE INC., INCLUDING CONTENT. YOU FURTHER ACKNOWLEDGE AND AGREE THAT THE VIEWS EXPRESSED ON THE WEB SITE DO NOT NECESSARILY REFLECT THE VIEWS OF WEBSTORE INC., AND WEBSTORE INC. DOES NOT SUPPORT OR ENDORSE CONTENT (INCLUDING ANY CONTRIBUTION, WHETHER OR NOT EDITED BY WEBSTORE INC. OR ITS DESIGNEE OR PRESENTED ON THE WEB SITE EDITED OR UNEDITED, IN WHOLE OR IN PART, OR ALONE OR WITH OTHER CONTENT) POSTED OR SUBMITTED BY YOU OR ANY USER.</p>

                <p><b>RESTRICTIONS ON USE OF MATERIAL</b></p>
                <p>THE CONTENT ON THIS WEB SITE IS INTENDED FOR ENTERTAINMENT PURPOSES ONLY. EXCEPT AS EXPRESSLY PERMITTED, YOU AGREE NOT TO USE THE WEB SITE FOR SALE, TRADE OR OTHER COMMERCIAL PURPOSES, AND, YOU MAY NOT MODIFY, COPY, PUBLISH, DISPLAY, TRANSMIT, ADAPT OR IN ANY WAY EXPLOIT THE CONTENT OF THE WEB SITE. ONLY IF YOU OBTAIN PRIOR WRITTEN CONSENT FROM US — AND FROM ALL OTHER ENTITIES WITH AN INTEREST IN THE RELEVANT INTELLECTUAL PROPERTY — MAY YOU PUBLISH, DISPLAY OR COMMERCIALLY EXPLOIT ANY MATERIAL FROM THE WEB SITE. TO SEEK OUR PERMISSION, YOU MAY WRITE TO US AT OUR ADDRESS PROVIDED BELOW. IF PERMISSION IS GRANTED BY US AND BY ALL OTHER ENTITIES WITH AN INTEREST IN THE RELEVANT INTELLECTUAL PROPERTY, YOU MAY NOT CHANGE OR DELETE ANY AUTHOR ATTRIBUTION, TRADEMARK, LEGEND OR COPYRIGHT NOTICE. YOU MUST ABIDE BY ALL ADDITIONAL COPYRIGHT NOTICES OR OTHER RESTRICTIONS CONTAINED ON THE WEB SITE.</p>

                <p><b>UNSOLICITED MATERIALS</b></p>
                <p>IN OPERATING THIS SITE, WEBSTORE INC. DOES NOT SOLICIT NOR DOES IT WISH TO RECEIVE ANY CONFIDENTIAL, SECRET OR PROPRIETARY INFORMATION OR OTHER MATERIAL FROM YOU THROUGH THE WEB SITE OR WEBSTORE INC. MAIL AND E-MAIL ADDRESSES, OR IN ANY OTHER WAY. ANY INFORMATION OR MATERIAL SUBMITTED OR SENT TO WEBSTORE INC., WILL BE DEEMED NOT TO BE CONFIDENTIAL OR SECRET. BY SUBMITTING OR SENDING INFORMATION OR OTHER MATERIAL TO WEBSTORE INC. YOU REPRESENT AND WARRANT THAT THE INFORMATION IS ORIGINAL TO YOU AND THAT NO OTHER PARTY HAS ANY RIGHTS TO THE MATERIAL.</p>

                <p><b>USER’S GRANT OF LIMITED LICENSE</b></p>
                <p>BY COMMUNICATING WITH WEBSTORE INC., INCLUDING SUBMITTING OR SENDING CONTENT, A CONTRIBUTION OR OTHER INFORMATION OR MATERIAL TO WEBSTORE.COM, YOU GRANT WEBSTORE INC. THE ROYALTY-FREE, UNRESTRICTED, WORLD-WIDE, PERPETUAL, IRREVOCABLE, NON-EXCLUSIVE AND FULLY SUB-LICENSABLE RIGHT AND LICENSE TO USE, REPRODUCE, MODIFY, ADAPT, PUBLISH, TRANSLATE, CREATE DERIVATIVE WORKS FROM, DISTRIBUTE, PERFORM AND DISPLAY SUCH CONTENT (IN WHOLE OR PART), INCLUDING ANY INFORMATION, SUGGESTIONS, IDEAS, DRAWINGS OR CONCEPTS CONTAINED IN SUCH CONTENT, WORLDWIDE AND/OR TO INCORPORATE IT IN OTHER WORKS IN ANY FORM, MEDIA, OR TECHNOLOGY NOW KNOWN OR LATER DEVELOPED. SUCH LICENSE INCLUDES INCORPORATING A CONTRIBUTION, IN WHOLE OR IN PART, INTO A WEBSTORE INC. FEATURE. YOU WILL REMAIN RESPONSIBLE FOR THE ACCURACY, COPYRIGHT COMPLIANCE, LEGALITY, DECENCY, OR ANY OTHER ASPECT OF SUCH SUBMITTED MATERIAL, INCLUDING ANY CONTRIBUTION OR PART THEREOF, OR OTHER COMMUNICATION TO WEBSTORE INC.. YOU ALSO WARRANT THAT ANY “MORAL RIGHTS” IN POSTED MATERIALS HAVE BEEN WAIVED.</p>

                <p><b>LINKED SITES</b></p>
                <p>YOU MAY BE ABLE TO LINK TO THIRD PARTIES’ WEB SITES (“LINKED SITES”) FROM THE WEBSTORE INC. WEB SITE. LINKED SITES ARE NOT, HOWEVER, REVIEWED, CONTROLLED, OR EXAMINED BY WEBSTORE INC. IN ANY WAY AND WEBSTORE INC. IS NOT RESPONSIBLE FOR THE CONTENT, AVAILABILITY, ADVERTISING, PRODUCTS OR OTHER MATERIALS OF ANY SUCH LINKED SITES, OR ANY ADDITIONAL LINKS CONTAINED THEREIN. THESE LINKS DO NOT IMPLY WEBSTORE INC.’S ENDORSEMENT OF OR ASSOCIATION WITH THE LINKED SITES. IT IS YOUR SOLE RESPONSIBILITY TO COMPLY WITH THE APPROPRIATE TERMS OF SERVICE OF THE LINKED SITES AS WELL AS WITH ANY OTHER OBLIGATION UNDER COPYRIGHT, SECRECY, DEFAMATION, DECENCY, PRIVACY, SECURITY AND EXPORT LAWS RELATED TO THE USE OF SUCH LINKED SITES AND ANY CONTENT CONTAINED THEREON. IN NO EVENT SHALL WEBSTORE INC. BE LIABLE, DIRECTLY OR INDIRECTLY, TO ANYONE FOR ANY LOSS OR DAMAGE ARISING FROM OR OCCASIONED BY THE CREATION OR USE OF THE LINKED SITES OR THE INFORMATION OR MATERIAL ACCESSED THROUGH THESE LINKED SITES. YOU SHOULD DIRECT ANY CONCERNS TO THAT SITE’S ADMINISTRATOR OR WEBMASTER. WEBSTORE INC. RESERVES THE EXCLUSIVE RIGHT, AT ITS SOLE DISCRETION, TO ADD, CHANGE, DECLINE OR REMOVE, WITHOUT NOTICE, ANY FEATURE OR LINK TO ANY OF THE LINKED SITES FROM THE WEB SITE AND/OR INTRODUCE DIFFERENT FEATURES OR LINKS TO DIFFERENT USERS.</p>

                <p>PERMISSION MUST BE GRANTED BY US FOR ANY TYPE OF LINK TO WEBSTORE.COM. TO SEEK OUR PERMISSION, YOU MAY WRITE TO WEBSTORE INC. WE RESERVE THE RIGHT, HOWEVER, TO RESCIND ANY PERMISSION GRANTED BY US TO LINK THROUGH ANY TYPE OF LINK, AND TO REQUIRE TERMINATION OF ANY SUCH LINK TO THE WEB SITE, AT OUR DISCRETION AT ANY TIME.</p>

                <p><b>PROMOTIONS</b></p>
                <p>FROM TIME TO TIME, WEBSTORE INC. MAY OFFER AS PART OF THE SERVICES, EITHER ON OR THROUGH THE WEB SITE, CONTESTS, POLLS OR PROMOTIONS (COLLECTIVELY, “PROMOTIONS”). TO PARTICIPATE IN PROMOTIONS, PLAYERS MAY BE REQUIRED TO COMPLETE A REGISTRATION FORM. UPON SUBMISSION, ALL REGISTRATIONS BECOME THE EXCLUSIVE PROPERTY OF WEBSTORE INC.. REGISTERED USERS (EACH, A “REGISTERED USER”) ARE PERMITTED ONLY ONE ACCOUNT. REGISTERED USERS WITH MORE THAN ONE ACCOUNT ARE SUBJECT TO IMMEDIATE DISQUALIFICATION FROM ANY PROMOTION, UNLESS THE DESCRIPTION OF THE PROMOTION EXPRESSLY INVITES A USER TO REGISTER MULTIPLE TIMES. WEBSTORE INC., AT ITS SOLE DISCRETION, MAY SUSPEND OR REVOKE THE REGISTRATION OF ANY REGISTERED USER.</p>

                <p>REGISTERED USERS AGREE TO RELEASE WEBSTORE INC. AND ITS AGENTS, SPONSORS OR PROMOTIONAL PARTNERS, FROM ALL LIABILITY ARISING FROM PARTICIPATION IN ANY OF PROMOTION LOCATED ON, OR ACCESSED THROUGH, THE WEB SITE. WEBSTORE INC. IS NOT RESPONSIBLE FOR TECHNICAL, HARDWARE OR SOFTWARE FAILURES OF ANY KIND, LOST OR UNAVAILABLE NETWORK CONNECTIONS, OR FAILED, INCOMPLETE, GARBLED OR DELAYED COMPUTER TRANSMISSIONS WHICH MAY LIMIT ANY REGISTERED USER’S ABILITY TO PARTICIPATE IN ANY PROMOTION.</p>

                <p>EACH REGISTERED USER AGREES TO BE BOUND BY THE RULES OF ANY PROMOTION AND BY THE RULES OF FAIR PLAY AND CONSIDERATION OF FELLOW REGISTERED USER. A REGISTERED USER WHO VIOLATES ANY OF THE RULES OR GUIDELINES FOR BEHAVIOR PUBLISHED ON THE WEB SITE, OR THE SITE WHERE THE PROMOTION IS CONDUCTED, ARE SUBJECT TO IMMEDIATE DISQUALIFICATION AND REVOCATION OF THEIR REGISTRATION. WEBSTORE INC. RESERVES THE RIGHT TO CANCEL, TERMINATE OR ALTER ANY PROMOTION OR THE RULES THEREOF AT ANY TIME WITHOUT PRIOR NOTIFICATION.</p>

                <p><b>INTELLECTUAL PROPERTY RIGHTS</b></p>
                <p>ALL MATERIALS CONTAINED IN THIS WEB SITE ARE THE COPYRIGHTED PROPERTY OF WEBSTORE INC. AND ITS AFFILIATES OR LICENSORS. AS BETWEEN WEBSTORE INC. AND YOU, WEBSTORE INC. IS THE SOLE OWNER OF ALL CONTENT ON THE WEB SITE, INCLUDING WITHOUT LIMITATION, ALL APPLICABLE U.S. AND NON-U.S. COPYRIGHTS, PATENTS, TRADEMARKS, AND TRADE SECRETS, AND OTHER INTELLECTUAL PROPERTY RIGHTS THERETO. EXCEPT AS OTHERWISE SPECIFICALLY PROVIDED IN THESE TERMS AND CONDITIONS, YOU MAY NOT DOWNLOAD OR SAVE A COPY OF THE WEB SITE OR ANY PORTION THEREOF, FOR ANY PURPOSE. YOU MAY, HOWEVER, PRINT A COPY OF INDIVIDUAL SCREENS APPEARING AS PART OF THE WEB SITE SOLELY FOR YOUR PERSONAL, NON-COMMERCIAL USE OR RECORDS, PROVIDED THAT ANY MARKS, LOGOS OR OTHER LEGENDS THAT APPEAR ON THE COPIED SCREENS REMAIN ON, AND ARE NOT REMOVED FROM THE PRINTED OR STORED IMAGES OF SUCH SCREENS. ALL TITLE AND INTELLECTUAL PROPERTY RIGHTS IN AND TO THE CONTENT OF THE LINKED SITES IS THE PROPERTY OF THE RESPECTIVE CONTENT OWNER AND MAY BE PROTECTED BY APPLICABLE COPYRIGHT OR OTHER INTELLECTUAL PROPERTY LAWS AND TREATIES.</p>

                <p><b>PARENTAL PERMISSION</b></p>
                <p>THIS WEB SITE IS NOT INTENDED TO BE A CHILDREN’S SITE, THEREFORE, SOME OF THE AVAILABLE INFORMATION MAY CONCERN CERTAIN TOPICS THAT MAY NOT BE APPROPRIATE FOR CHILDREN. WEBSTORE INC. MAY, AT ITS DISCRETION, REQUIRE USERS UNDER 18 TO OBTAIN THE CONSENT OF A PARENT OR GUARDIAN TO VIEW CERTAIN CONTENT, AND WEBSTORE INC. MAY LIMIT ACCESS TO CERTAIN CONTENT TO USERS ABOVE A SPECIFIED AGE. YOU AGREE TO ABIDE BY ANY SUCH RESTRICTIONS, AND NOT TO HELP ANYONE AVOID THESE RESTRICTIONS.</p>

                <p><b>PRIVACY POLICY</b></p>
                <p>WE ARE COMMITTED TO PROTECTING YOUR PRIVACY AND SECURITY AND HAVE EXPLAINED IN DETAIL THE STEPS WE TAKE TO DO SO. WE URGE YOU TO READ OUR PRIVACY POLICY.</p>

                <p><b>DISCLAIMER OF WARRANTIES</b></p>
                <p>THE WEB SITE AND SERVICES ARE PROVIDED “AS IS,” “WHERE IS” AND “AS AVAILABLE,” WITHOUT WARRANTY OF ANY KIND, EITHER EXPRESS OR IMPLIED. WITHOUT LIMITATION OF THE FOREGOING, WEBSTORE INC. SPECIFICALLY DISCLAIMS ANY AND ALL WARRANTIES, INCLUDING, BUT NOT LIMITED TO: (I) ANY WARRANTIES CONCERNING THE AVAILABILITY, ACCURACY, APPROPRIATENESS, RELIABILITY, TIMELINESS, USEFULNESS, OR OTHERWISE OF THE CONTENT OF THE WEB SITE OR SERVICES; AND (II) ANY WARRANTIES OF TITLE, WARRANTY OF NON-INFRINGEMENT, WARRANTIES OF MERCHANTABILITY OR FITNESS FOR A PARTICULAR PURPOSE. THIS DISCLAIMER OF LIABILITY APPLIES TO ANY DAMAGES OR INJURY CAUSED BY THE WEB SITE, INCLUDING WITHOUT LIMITATION AS A RESULT OF (1) ANY ERROR, OMMISSION, DELETION OR DEFECT IN THE CONTENT, OR (2) ANY FAILURE OF PERFORMANCE, ERROR, OMISSION, INTERRUPTION, DELETION, DEFECT, DELAY IN OPERATION OR TRANSMISSION, COMPUTER VIRUS, COMMUNICATION LINE FAILURE, THEFT OR DESTRUCTION OR UNAUTHORIZED ACCESS TO, ALTERATION OF, OR USE OF RECORD, WHETHER FOR BREACH OF CONTRACT, TORT, NEGLIGENCE, DEFAMATION OR UNDER ANY OTHER CAUSE OF ACTION. WEBSTORE INC. DOES NOT WARRANT OR GUARANTEE (1) THAT ANY PORTION OF THE WEB SITE WILL BE FREE OF INFECTION BY VIRUSES, WORMS, TROJAN HORSES OR ANYTHING ELSE MANIFESTING CONTAMINATING OR DESTRUCTIVE PROPERTIES; OR (2) THAT ACCESS TO THE WEB SITE WILL BE UNINTERRUPTED OR ERROR-FREE.</p>

                <p>WEBSTORE INC. DOES NOT WARRANT OR MAKE ANY REPRESENTATIONS REGARDING THE USE OR THE RESULTS OF THE USE OF THE MATERIALS IN THIS WEB SITE. YOU (AND NOT WEBSTORE INC. OR ANY OF ITS AGENTS) ASSUME THE ENTIRE COST OF ALL NECESSARY SERVICING, REPAIR OR CORRECTION.</p>

                <p>APPLICABLE LAW MAY NOT ALLOW THE EXCLUSION OF IMPLIED WARRANTIES, SO THE ABOVE EXCLUSION MAY NOT APPLY TO YOU.</p>

                <p><b>LIMITATION OF LIABILITY</b></p>
                <p>IN NO EVENT WILL WEBSTORE INC., ITS OFFICERS, DIRECTORS, EMPLOYEES, CONTRACTORS AGENTS, SPONSORS, ADVERTISERS, PARENTS, AFFILIATES, SUCCESSORS OR ASSIGNS, BE LIABLE TO ANY PARTY (I) FOR ANY INDIRECT, SPECIAL, PUNITIVE, INCIDENTAL OR CONSEQUENTIAL DAMAGES OR ANY OTHER DAMAGES ARISING IN ANY WAY OUT OF THE AVAILABILITY, USE, RELIANCE ON, OR INABILITY TO USE THE WEB SITE, EVEN IF WEBSTORE INC. OR ITS AGENTS SHALL HAVE BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, AND REGARDLESS OF THE FORM OF ACTION, WHETHER IN CONTRACT, TORT, OR OTHERWISE; OR (II) FOR ANY CLAIM ATTRIBUTABLE TO ERRORS, OMISSIONS, OR OTHER INACCURACIES IN, OR DESTRUCTIVE PROPERTIES OF THE WEB SITE. BECAUSE SOME STATES OR JURISDICTIONS DO NOT ALLOW THE EXCLUSION OR THE LIMITATION OF LIABILITY FOR CONSEQUENTIAL OR INCIDENTAL DAMAGES, IN SUCH STATES OR JURISDICTIONS, WEBSTORE INC.’S LIABILITY SHALL BE LIMITED TO THE EXTENT PERMITTED BY LAW.</p>

                <p><b>INDEMNIFICATION</b></p>
                <p>UPON A REQUEST BY WEBSTORE INC., YOU AGREE TO DEFEND, INDEMNIFY AND HOLD WEBSTORE INC., ITS AFFILIATES, OFFICERS, DIRECTORS AND EMPLOYEES AND CONTRACTORS HARMLESS FROM ANY AND ALL CLAIMS, LIABILITIES, COSTS AND EXPENSES, INCLUDING REASONABLE ATTORNEYS’ FEES, ARISING IN ANY WAY FROM YOUR USE OR MISUSE OF THE WEB SITE OR SERVICES, OR THE UPLOADING, POSTING, PUBLISHING, E-MAILING, REPRODUCTION, DISTRIBUTION OR TRANSMISSION OF ANY CONTENT OR OTHER MATERIALS BY YOU OR USERS AUTHORIZED BY YOU OR ANY VIOLATION OF THESE TERMS AND CONDITIONS BY YOU. WEBSTORE INC. RESERVES THE RIGHT, AT ITS OWN EXPENSE, TO ASSUME THE EXCLUSIVE DEFENSE AND CONTROL OF ANY MATTER OTHERWISE SUBJECT TO INDEMNIFICATION BY YOU, IN WHICH EVENT YOU WILL COOPERATE WITH WEBSTORE INC. IN ASSERTING ANY AVAILABLE DEFENSE.</p>

                <p><b>APPLICABLE LAWS/JURISDICTION</b></p>
                <p>YOU AGREE THAT THE LAWS OF THE STATE OF NEW YORK, EXCLUDING ITS CONFLICTS-OF-LAW RULES, SHALL GOVERN THESE TERMS AND CONDITIONS. PLEASE NOTE THAT YOUR USE OF THE WEB SITE MAY BE SUBJECT TO OTHER LOCAL, STATE, NATIONAL, AND INTERNATIONAL LAWS. YOU EXPRESSLY AGREE THAT EXCLUSIVE JURISDICTION FOR ANY CLAIM OR DISPUTE WITH WEBSTORE INC. OR RELATING IN ANY WAY TO YOUR USE OF THE WEB SITE RESIDES IN THE COURTS OF THE STATE OF NEW YORK, AND YOU FURTHER AGREE AND EXPRESSLY CONSENT TO THE EXERCISE OF PERSONAL JURISDICTION IN THE COURTS OF THE STATE OF NEW YORK, IN CONNECTION WITH ANY SUCH DISPUTE AND INCLUDING ANY CLAIM INVOLVING WEBSTORE INC. OR ITS AFFILIATES, SUBSIDIARIES, EMPLOYEES, CONTRACTORS, OFFICERS, DIRECTORS, TELECOMMUNICATION PROVIDERS AND CONTENT PROVIDERS.</p>

                <p>WE CONTROL AND OPERATE THIS SITE FROM OUR OFFICES IN NEW YORK, NEW YORK. WE DO NOT REPRESENT THAT MATERIALS ON THE SITE ARE APPROPRIATE OR AVAILABLE FOR USE OUTSIDE OF NEW YORK, NEW YORK. PERSONS WHO CHOOSE TO ACCESS THIS SITE FROM OTHER LOCATIONS DO SO ON THEIR OWN INITIATIVE, AND ARE RESPONSIBLE FOR COMPLIANCE WITH LOCAL LAWS, IF AND TO THE EXTENT LOCAL LAWS ARE APPLICABLE.</p>

                <p><b>ASSIGNMENT</b></p>
                <p>YOU SHALL NOT TRANSFER, ASSIGN, SUBLICENSE NOR PLEDGE IN ANY MANNER WHATSOEVER, ANY OF YOUR RIGHTS OR OBLIGATIONS UNDER THIS AGREEMENT. WEBSTORE INC. MAY TRANSFER, ASSIGN SUBLICENSE OR PLEDGE IN ANY MANNER WHATSOEVER, ANY OF ITS RIGHTS AND OBLIGATIONS UNDER THIS AGREEMENT TO A SUBSIDIARY, AFFILIATE, OR SUCCESSOR THEREOF OR TO ANY THIRD PARTY WHATSOEVER, WITHOUT NOTIFYING YOU OR RECEIVING YOUR CONSENT.</p>

                <p>PLEASE CONTACT US IF YOU HAVE ANY QUESTIONS ABOUT THIS POLICY OR OUR SITE IN GENERAL.</p>

                <p><b>PRIVACY POLICY</b></p>
                <p>WEBSTORE INC. TAKES SERIOUSLY THE PRIVATE NATURE OF YOUR PERSONAL INFORMATION. THIS PRIVACY POLICY DESCRIBES HOW WE TREAT THE INFORMATION WE COLLECT WHEN YOU VISIT OUR WEBSITE AND/OR REGISTER TO VIEW THE SITE. PLEASE READ THIS NOTICE CAREFULLY.</p>

                <p><b>PERSONAL INFORMATION</b></p>
                <p>IN ORDER TO SUPPLY YOU WITH YOUR WEBSTORE INC. E-MAIL, WE NEED YOUR E-MAIL ADDRESS. SIMILARLY, IN ORDER TO SUPPLY YOU WITH ANY TEXT-MESSAGING SERVICES, WE NEED YOUR PHONE NUMBER AND YOUR PROVIDER INFORMATION. SO THAT WE MAY PROVIDE YOU WITH ADDITIONAL SERVICES, WE MAY ALSO REQUEST YOUR NAME, TELEPHONE NUMBER OR OTHER INFORMATION. WEBSTORE INC. DOES NOT COLLECT ANY PERSONAL INFORMATION THAT YOU DO NOT EXPRESSLY PROVIDE. WEBSTORE INC. WILL NEVER SELL, RENT, OR SHARE YOUR PERSONALLY IDENTIFIABLE INFORMATION WITH ANY THIRD PARTIES FOR MARKETING PURPOSES WITHOUT YOUR EXPRESS PERMISSION. WEBSTORE INC. MAY SHARE YOUR PERSONAL INFORMATION FOR THE PURPOSE OF DELIVERING E-MAIL TO YOU OR AS REQUIRED BY LAW.</p>

                <p><b>NON-PERSONAL INFORMATION</b></p>
                <p>WEBSTORE INC. MAY ALSO REQUEST NON-PERSONALLY IDENTIFIABLE INFORMATION, SUCH AS ANNUAL INCOME, BUYING PREFERENCES, OR AGE, ALSO KNOWN AS DEMOGRAPHIC AND PROFILE DATA. THOUGH THIS INFORMATION IS OPTIONAL, WE MAY USE IT TO IMPROVE OUR SITE AND/OR TAILOR YOUR EXPERIENCE ON OUR SITE, SHOWING YOU CONTENT THAT WE THINK YOU MIGHT BE INTERESTED IN AND DISPLAYING CONTENT ACCORDING TO YOUR PREFERENCES. WE MAY ALSO SHARE THIS INFORMATION WITH OTHERS, SUCH AS POTENTIAL ADVERTISERS INTERESTED IN ADVERTISING IN THE WEBSTORE INC. E-MAIL OR ON THE SITE, IN AGGREGATE, ANONYMOUS FORM, WHICH MEANS THAT THE INFORMATION WILL NOT CONTAIN ANY PERSONALLY IDENTIFIABLE INFORMATION ABOUT YOU OR ANY OTHER PERSON.</p>

                <p><b>USAGE INFORMATION</b></p>
                <p>IN ADDITION TO COLLECTING PERSONAL AND NON-PERSONAL INFORMATION, WEBSTORE INC. MAY ALSO COLLECT NON-PERSONAL, AGGREGATED INFORMATION ABOUT SUBSCRIBERS’ USE OF WEBSTORE INC. E-MAILS AND THE WEBSITE. THIS INFORMATION IS NOT PERSONALLY IDENTIFIABLE AND WILL BE USED ONLY TO FIND OUT HOW SUBSCRIBERS USE OUR SERVICE AND SITE. FOR EXAMPLE, THIS INFORMATION WILL TELL US HOW MUCH TIME USERS SPEND ON THE WEBSTORE INC. SITE, FROM WHICH SITES SUBSCRIBERS CAME, AND TO WHAT SITES SUBSCRIBERS GO.</p>

                <p><b>THIRD-PARTY ADVERTISING</b></p>
                <p>SOME OF THE ADVERTSING APPEARING ON THIS WEBSITE MAY BE DELIVERED TO YOU BY OUR WEB SPONSORING PARTNERS. INFORMATION ABOUT YOUR VISIT TO THEIR SITE, SUCH AS THE NUMBER OF TIMES YOU HAVE VIEWED AN ADVERTISEMENT (BUT NOT YOUR NAME, ADDRESS, OR OTHER PERSONAL INFORMATION), IS USED TO SERVE ADS TO YOU.</p>

                <p><b>TRACKING</b></p>
                <p>LIKE MOST SITES, WEBSTORE INC. MAY MAKE USE OF BROWSER COOKIES. COOKIES ARE SMALL TEXT FILES PLACED ON YOUR COMPUTER’S HARD DISK BY OUR SERVER. THEY ALLOW US TO QUICKLY CHECK YOUR STATUS AS A SUBSCRIBER AND FACILITATE ACCESS TO YOUR PREFERENCES. WEBSTORE INC. WILL NEVER USE COOKIES TO RETRIEVE INFORMATION FROM A COMPUTER THAT IS UNRELATED TO OUR SITE OR SERVICES. WEBSTORE INC. ALSO USES TRANSPARENT GIF IMAGES. WE USE THESE IMAGES TO TRACK THE E-MAILS THAT WE SEND OUT.</p>

                <p><b>THIRD-PARTY COOKIES</b></p>
                <p>IN THE COURSE OF SERVING ADVERTISEMENTS TO THIS SITE, OUR THIRD-PARTY ADVERTISERS MAY PLACE OR RECOGNIZE A UNIQUE COOKIE ON YOUR BROWSER.</p>

                <p><b>LINKS TO OTHER SITES</b></p>
                <p>AS PART OF THE SERVICE, WEBSTORE INC. MAY CREATE LINKS ALLOWING YOU TO ACCESS THIRD-PARTY SITES. WEBSTORE INC. IS NOT RESPONSIBLE FOR THE CONTENT THAT APPEARS ON THESE SITES AND DOES NOT ENDORSE THESE SITES. PLEASE CONSULT THE SITES’ INDIVIDUAL PRIVACY POLICIES IN ORDER TO DETERMINE HOW THEY TREAT USER INFORMATION.</p>

                <p><b>MODIFICATION TO THIS POLICY</b></p>
                <p>WEBSTORE INC. MAY CHANGE THIS POLICY AT ANY TIME, WHICH CHANGES SHALL BE EFFECTIVE UPON POSTING HERE.</p>

                <p><b>CONTACT US</b></p>
                <p>IF YOU HAVE ANY QUESTIONS ABOUT THIS POLICY OR OUR SITE IN GENERAL, PLEASE CONTACT US AT INFO@WEBSTORE.COM</p>
                
            </div> <!-- /.inner-div -->
        </div> <!-- /.container -->
        <%@include file="footer.jsp"%>

    </body>
</html>
